[package]
name = "helix-dap"
description = "DAP client implementation for Helix project"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helix-stdx = { path = "../helix-stdx" }
helix-core = { path = "../helix-core" }
helix-dap-types = { path = "../helix-dap-types" }

anyhow = { default-features = false, version = "1.0" }
log = "0.4"
serde = { version = "1.0", default-features = false }
serde_json = { default-features = false, version = "1.0" }
tokio = { version = "1", features = ["rt", "io-util", "process", "net"], default-features = false }
thiserror.workspace = true
slotmap.workspace = true
futures-executor.workspace = true
futures-util.workspace = true
tokio-stream.workspace = true
sonic-rs.workspace = true
